rancher/tfp-automation

functions/wait/action/kubernetesUpgrade.go, functions/wait/action/scaleDown.go, functions/wait/action/scaleUp.go, functions/wait/state/activeAndReady.go, functions/wait/state/activeNodes.go, functions/wait/state/waitingOrUpdating.go, functions/wait/waitFor.go
resolves logging regression caused by copy/paste error
=> logging fix

config/config.go, framework/set/provisioning/setAKS.go, framework/set/provisioning/setBaselinePSACT.go, framework/set/provisioning/setConfigTF.go, framework/set/provisioning/setEKS.go, framework/set/provisioning/setGKE.go, framework/set/provisioning/setProvidersTF.go, framework/set/provisioning/setRKE1Config.go, framework/set/provisioning/setRKE2K3sConfig.go, tests/psact/README.md, tests/psact/psact_test.go
Issue: https://github.com/rancher/qa-tasks/issues/1216
=> adds support for rancher-baseline psact

go.mod, go.sum, pipeline/qase/reporter/main.go, pipeline/qase/testcase/testcase.go, tests/provisioning/provision_test.go, tests/upgrading/kubernetes_upgrade_test.go
PIT team recently updated the Qase parser to make the test cases more readable. This PR is matching the work done there, but for `tfp-automation`.
=> Update Qase to match rancher/rancher

tests/nodescaling/scale_hosted_test.go, tests/nodescaling/scale_test.go, tests/provisioning/provision_hosted_test.go, tests/provisioning/provision_test.go, tests/psact/psact_test.go, tests/snapshot/snapshot_restore_k8s_upgrade_test.go, tests/snapshot/snapshot_restore_test.go, tests/snapshot/snapshot_restore_upgrade_strategy_test.go, tests/upgrading/kubernetes_hosted_test.go, tests/upgrading/kubernetes_upgrade_test.go
Reverts rancher/tfp-automation#25
=> Revert "Update function names to be generic"

pipeline/qase/reporter/main.go
Qase reporting is not picking up results from runs. This is most likely from past constants work done, so making needed changes.
=> Fix Qase reporting issues

Dockerfile, Jenkinsfile, Jenkinsfile_vpn, go.mod
Simple updates to the Jenkinsfile and Dockerfile.
=> Update Jenkinsfile and Dockerfile

framework/set/provisioning/custom/locals/setLocals.go
Fixing what I broke 🫣 
forgot to update and tag clusterName as prefix to locals block node commands
=> tag clusterName to setLocals for non-multicluster custom clusters

Jenkinsfile, Jenkinsfile_vpn
Small PR that is needed due to backend Jenkins changes causing credentials to not be read in correctly.
=> Replace config variables to properly read credentials

config/config.go, framework/set/resources/airgap/createMainTF.go, framework/set/resources/airgap/rancher/setup.sh, framework/set/resources/airgap/rancher/setupAirgapRancher.go, framework/set/resources/airgap/rke2/add-servers.sh, framework/set/resources/airgap/rke2/createAirgapCluster.go, framework/set/resources/airgap/rke2/init-server.sh, framework/set/resources/registries/auth-registry.sh, framework/set/resources/registries/createRegistry.go, framework/set/resources/registries/non-auth-registry.sh, framework/set/resources/sanity/aws/createResources.go, framework/set/resources/sanity/createMainTF.go, framework/set/resources/sanity/rancher/createRancher.go, framework/set/resources/sanity/rancher/setup.sh, tests/airgap/README.md, tests/sanity/README.md
During release testing, there was an issue found with using the staging registry. The correct rancher and rancher-agent images are not being pulled. This PR fixes that issue.
=> Fix issue with rancher staging images not pulling in airgap environments

framework/set/provisioning/custom/locals/setLocals.go, framework/set/provisioning/custom/nullresource/setNullResource.go, framework/set/provisioning/custom/nullresource/setWindowsNullResource.go, framework/set/resources/registries/createRegistry/auth-registry.sh, framework/set/resources/registries/createRegistry/non-auth-registry.sh, framework/set/resources/sanity/rancher/createRancher.go, framework/set/setAuthConfig.go, framework/set/setConfigTF.go, tests/airgap/airgap_provisioning_test.go, tests/airgap/airgap_upgrade_rancher_test.go, tests/extensions/rbac/authConfig.go, tests/proxy/proxy_provisioning_test.go, tests/proxy/proxy_upgrade_rancher_test.go, tests/rancher2/nodescaling/scale_test.go, tests/rancher2/provisioning/README.md, tests/rancher2/provisioning/provision_custom_test.go, tests/rancher2/provisioning/provision_test.go, tests/rancher2/psact/psact_test.go, tests/rancher2/rbac/README.md, tests/rancher2/rbac/auth_test.go, tests/rancher2/rbac/rbac_test.go, tests/rancher2/snapshot/snapshot_restore_test.go, tests/rancher2/upgrading/kubernetes_upgrade_test.go, tests/registries/registries_test.go, tests/sanity/tfp_automation_sanity_test.go
During release testing, it was noted that there were multiple issues found, see the list below:
- Rancher2 tests were not running
- Custom RKE2 Windows appeared to have a regression
- Using the staging registry for the sanity test flat out is not working
- Temporarily removing RKE2 Windows airgap check due to intermittent issue happening
This PR fixes the above issues.
=> Fix miscellaneous issues found during release testing

framework/cleanup/cleanup.go
Added an if statement to fix cleanup error
=> Fix cleanup

config/config.go, framework/set/resources/providers/aws/instances.go, framework/set/resources/registries/createMainTF.go, framework/set/resources/registries/createRegistry/createRegistry.go, framework/set/resources/registries/createRegistry/ecr-registry.sh, modules/registries/aws/outputs.tf, tests/registries/README.md, tests/registries/registries_test.go
integrating ECR registry checks into `tfp-automation`
=> enhancement to support ecr registries

.github/workflows/verify-changes.yaml
Small PR to update the `verify-changes.yaml` to remove the `push` trigger and update checkout to `v4`.
=> Update verify-changes workflow

.github/workflows/sanity-upgrade-test.yaml, tests/sanity/sanity_upgrade_rancher_test.go
This PR adds support for the sanity upgrade job to run every Monday.
=> Add sanity upgrade workflow

.github/actions/get-ecr-password/action.yaml, .github/actions/get-latest-rancher-tag/action.yaml, .github/actions/revoke-runner-ip/action.yaml, .github/actions/whitelist-runner-ip/action.yaml, .github/workflows/check-rancher-tag.yaml, .github/workflows/registry-test.yaml, framework/set/resources/registries/createRegistry/createRegistry.go, tests/registries/registries_test.go
implements registry testing to a GHA workflow, and adds an action to retrieve and set ECR password for testing.
NOTE TO REVIEWERS:
the current "pr" related trigger is only for testing + verifying this workflow is functional.  Once the workflow as proven to be successful, i'll update the PR to remove the "pr" related trigger 🙂 
specifically this portion of the trigger will be removed, upon a successful run:
```yaml
pull_request:
branches:
- main
```
=> GitHub Actions workflows for registries

.github/workflows/airgap-test.yaml, .github/workflows/airgap-upgrade-test.yaml, .github/workflows/check-rancher-tag.yaml, .github/workflows/registry-test.yaml, tests/airgap/airgap_provisioning_test.go, tests/airgap/airgap_upgrade_rancher_test.go
As part of broader efforts to have the tfp-automation infrastructure tests migrate over to GHA, the airgap tests are the last ones needed to finish this task.
=> Add airgap GHA workflows

.github/workflows/airgap-test.yaml, .github/workflows/airgap-upgrade-test.yaml, .github/workflows/proxy-test.yaml, .github/workflows/proxy-upgrade-test.yaml, .github/workflows/registry-test.yaml, .github/workflows/sanity-test.yaml, .github/workflows/sanity-upgrade-test.yaml
removes `required` bool from `rancher_version` workflow dispatch triggers
=> update required trigger field for rancher_version

.github/workflows/airgap-test.yaml, .github/workflows/airgap-upgrade-test.yaml, .github/workflows/pr-sanity-test.yaml, .github/workflows/proxy-test.yaml, .github/workflows/proxy-upgrade-test.yaml, .github/workflows/rancher2-recurring-test.yaml, .github/workflows/registry-test.yaml, .github/workflows/sanity-test.yaml, .github/workflows/sanity-upgrade-test.yaml
This PR enhances our use of AWS creds to use AWS Secrets Manager instead of using personal creds.
=> Enhance AWS creds to use AWS Secrets Manager

framework/set/resources/registries/createRegistry/createRegistry.go
fixes registry pathing, which broke in Jenkins.  This should allow both jenkins + GHA to be functional.
=> fix registry pathing

.github/actions/check-rancher-tag/action.yaml, .github/actions/get-latest-rancher-tag/action.yaml, .github/workflows/check-rancher-tag.yaml
In this latest release testing, we noted that there were some issues with the `check-rancher-tag` workflow. This PR aims to address some of those issues and see if it is functional now.
=> Update check rancher tag workflow

.github/workflows/check-rancher-tag.yaml
Reverts rancher/tfp-automation#175
=> Revert "Testing for check-rancher-tag - revert after"

.github/workflows/airgap-test.yaml, .github/workflows/airgap-upgrade-test.yaml, .github/workflows/registry-test.yaml
There is a potential parentheses grouping issue with registry and airgap workflows. This is preventing us from manually running the workflows when we should be able to.
=> Fix if conditional grouping for registry and airgap

.github/workflows/airgap-test.yaml, .github/workflows/airgap-upgrade-test.yaml
The airgap workflows haven't been updated to use the Docker Teams account. Small PR to fix that issue.
=> Update airgap workflows to use Docker Teams account

.github/workflows/airgap-test.yaml, .github/workflows/airgap-upgrade-test.yaml
Airgap is still failing in the workflows and it is because in the last PR, neglected to update the registry credentials in the `terraform` block....
=> Add missing params in airgap workflows

.github/workflows/registry-test.yaml
As it nears 5PM, silly mistakes are being made. The last PR uses the incorrect registry credentials (as if the names weren't confusing enough already).
=> Fix incorrect private registry creds
