- Jenkinsfile
In the Jenkins job, there's some confusion with how `run` is defined in the test case description. On further inspection, we're incorrectly specifying `run` in the Jenkinsfile. This small PR removes that to be on 1:1 with the Jenkinsfile in the Go framework.
> Remove -run in the Jenkinsfile

- Dockerfile
- Jenkinsfile
- Jenkinsfile_vpn
- README.md
- config/config.go
- framework/set/provisioning/setProvidersTF.go
- scripts/setup-provider.sh
- tests/extensions/provisioning/buildModule.go
- tests/resources/build_module_test.go
This PR:
- enhances tfp-automation repo to be able to test via Rancher2 RCs
- fixes poor formatting w/ `BuildModule` test output, caused by logrus
- pulls `providerVersion` out of Terraform config, which is replaced with `RANCHER2_PROVIDER_VERSION` env variable
- enhances repo to allow configurable terraform version -- utilizing `TERRAFORM_VERSION` env variable
- updates `readme.md`, pertaining to `providerVersion` field being pulled out, and new env variable `RANCHER2_PROVIDER_VERSION`
> enhance tfp-automation to allow testing against rancher2 RCs

- Dockerfile
- README.md
- framework/set/provisioning/setProvidersTF.go
- framework/set/provisioning/setRKE1Config.go
- framework/set/provisioning/setRKE2K3sConfig.go
- go.mod
- go.sum
- tests/nodescaling/README.md
- tests/nodescaling/scale_test.go
- tests/snapshot/README.md
- tests/snapshot/snapshot.go
- tests/snapshot/snapshot_restore_k8s_upgrade_test.go
- tests/snapshot/snapshot_restore_test.go
- tests/snapshot/snapshot_restore_upgrade_strategy_test.go
As part of ongoing additional etcd snapshot coverage, there are constant changes going on. As such, we will need to make sure that the `tfp-automation` framework accommodates where it makes sense to do so.
- Restructures `snapshot` package based upon latest `rancher/rancher` snapshot package changes.
- Removes RKE1 clusters from the `snapshot` package.
- Gives needed stability in flakiness found during release testing in the snapshot tests.
- Makes specifying etcd blocks optional when provisioning RKE1/RKE2/K3S clusters
- Unrelated to the snapshot tests, but good to have this in and small change.
Jenkins jobs will be provided offline to the reviewers.
> Restructure `snapshot` package to match `rancher/rancher` snapshot package

- README.md
- config/config.go
- tests/snapshot/README.md
- tests/snapshot/snapshot.go
- tests/snapshot/snapshot_restore_k8s_upgrade_test.go
- tests/snapshot/snapshot_restore_test.go
- tests/snapshot/snapshot_restore_upgrade_strategy_test.go
In providing a `tfp-automation` counterpart PR for QA task https://github.com/rancher/qa-tasks/issues/1143, it was noted that recurring restores go against the best practices of the `tfp-automation` repo. Specifically, restoring multiple times will not work as the `main.tf` does not change.
As such, Terraform will not proceed forward. As that is the case, we are already covering the functionality of recurring restores, so there is no need to duplicate effort here.
> Remove recurring restores from snapshot test suite

- tests/extensions/provisioning/kubernetesUpgrade.go
- tests/upgrading/README.md
- tests/upgrading/kubernetes_upgrade_test.go
Currently, the `tfp-automation` framework allows for upgrading downstream clusters. This is done through the `upgradedKubernetesVersion` in the `terratest` config block. You will need to set the version in order for the test to work.
This PR enhances the test so that if that parameter is blank or non-existent, then the latest K8s version available be used to upgrade the downstream cluster. We have this functionality in the Go framework, so it should be here as well.
> Enhance upgrade test to use default K8s version if none selected

- Dockerfile
- Jenkinsfile
- Jenkinsfile_vpn
- go.mod
- go.sum
- pipeline/qase/defaults.go
- pipeline/qase/reporter/main.go
- pipeline/qase/testcase/testcase.go
- pipeline/qase/testrun/main.go
- pipeline/scripts/build_qase_reporter.sh
Issue: https://github.com/rancher/qa-tasks/issues/1219
We are using Qase for internal tracking of automation in rancher/rancher tests that we run. We should ensure that we have this happening for the `tfp-automation` tests as well.
As there are underlying architecture differences from rancher/rancher and rancher/tfp-automation, there is duplicate code being copied over in this PR. Specifically, the `pipeline` folder is what is being copied over.
> Implement Qase with tfp-automation

- framework/set/provisioning/setRKE1Config.go
- framework/set/provisioning/setRKE2K3sConfig.go
When using a node provider like Linode, you are not permitted to have duplicate naming with your instances. As a result, the cluster never provisions as the node never comes up.
For node providers like AWS, they allow duplicate names. This PR avoids naming conflicts to not hit this problem.
> Update cluster pool names to avoid name conflicts

- framework/set/provisioning/setConfigTF.go
- framework/set/provisioning/setRKE1Config.go
- framework/set/provisioning/setRKE2K3sConfig.go
- framework/setup.go
- tests/extensions/provisioning/buildModule.go
- tests/extensions/provisioning/kubernetesUpgrade.go
- tests/extensions/provisioning/provision.go
- tests/extensions/provisioning/scale.go
- tests/nodescaling/scale_test.go
- tests/provisioning/provision_test.go
- tests/psact/psact_test.go
- tests/snapshot/snapshot.go
- tests/snapshot/snapshot_restore_k8s_upgrade_test.go
- tests/snapshot/snapshot_restore_test.go
- tests/snapshot/snapshot_restore_upgrade_strategy_test.go
- tests/upgrading/kubernetes_upgrade_test.go
When running non-provisioning tests such as nodescaling, the `main.tf` was resetting the node pool/machine pool name. This was causing failures in tests. As a result, we were unable to properly get passing tests.
This enhances this and fixes the failures we were seeing.
> Enhance dynamic naming for cluster machine pools

- README.md
- config/nodeproviders/google_config.go
- framework/set/provisioning/setAKS.go
- framework/set/provisioning/setGKE.go
- framework/wait/state/activeCluster.go
- framework/wait/state/activeNodes.go
- tests/extensions/provisioning/verify.go
- tests/nodescaling/README.md
- tests/nodescaling/scale_hosted_test.go
- tests/provisioning/README.md
- tests/provisioning/provision_hosted_test.go
- tests/psact/README.md
- tests/snapshot/README.md
- tests/upgrading/README.md
- tests/upgrading/kubernetes_hosted_test.go
The `tfp-automation` framework supported hosted clusters as part of the initial MVP. However, as it was passed off to the highlanders team, this overtime has become outdated code in the framework. As it seems there's been more of an ask to have hosted clusters again, this PR is updating the outdated code.
Additionally, it fixes underlying issues found such as the need to have them separated into their own test files. Provisioning, upgrading and node scaling are supported for AKS/EKS/GKE.
> Refactor hosted clusters tests

- defaults/configs/configs.go
- tests/extensions/provisioning/defaultK8sVersion.go
- tests/nodescaling/scale_hosted_test.go
- tests/nodescaling/scale_test.go
- tests/provisioning/provision_hosted_test.go
- tests/provisioning/provision_test.go
- tests/psact/psact_test.go
- tests/snapshot/snapshot_restore_k8s_upgrade_test.go
- tests/snapshot/snapshot_restore_test.go
- tests/snapshot/snapshot_restore_upgrade_strategy_test.go
- tests/upgrading/kubernetes_upgrade_test.go
For the `upgrading` package, we currently are having the static tests use `kubernetesVersion` initially set. We don't want to do this as since it is a static test, we should not have to rely on the config more than needed. To get around this, static tests will by default get the second highest K8s version and then upgrade to the latest K8s versions.
Dynamic tests are still free to pull whatever initial version it wants and upgrade to whatever vresion it wants.
> Allow second highest K8s version to be statically set

- tests/snapshot/snapshot_restore_k8s_upgrade_test.go
- tests/snapshot/snapshot_restore_test.go
- tests/snapshot/snapshot_restore_upgrade_strategy_test.go
As `tfp-automation` is primarily focused on testing `rancher2` resources, there is no need to test every permutation of test cases. Especially when we do that with `rancher/rancher`. This PR cuts back on that for the `snapshot` package.
Additionally, it distinguishes when an S3 backup is being ran vs a local backup. This is primarily for Qase reporting.
> Test only dedicated roles for `snapshot` package and distinguish S3 and local etcd backups

- config/config.go
- framework/set/defaults/defaults.go
- framework/set/provisioning/rke1/setNodePool.go
- go.mod
- go.sum
- tests/nodescaling/scale_test.go
- tests/provisioning/provision_test.go
- tests/snapshot/snapshot.go
- tests/upgrading/kubernetes_upgrade_test.go
This PR is the tfp-automation counterpart to the linked issue. In addition, the following is done:
- Cuts back testing to just dedicated clusters to save resources / shave duplication efforts done in rancher/rancher
- Update RKE1 nodepool names (mostly for nodescaling)
> Update snapshot.go to match rancher/rancher

- Jenkinsfile
- Jenkinsfile_vpn
Currently, Qase is only reporting successful runs and not failures. Obviously, we need both scenarios to work within Qase. This is a small PR to address that.
> Address Qase not reporting failures

- config/config.go
- framework/set/provisioning/hosted/setAKS.go
- framework/set/provisioning/hosted/setEKS.go
- framework/set/provisioning/hosted/setGKE.go
- framework/set/provisioning/rke1/setConfig.go
- framework/set/provisioning/rke2k3s/setConfig.go
- framework/set/rbac/setProject.go
- framework/set/rbac/setUsers.go
- framework/set/setConfigTF.go
- framework/setup.go
- tests/extensions/provisioning/buildModule.go
- tests/extensions/provisioning/kubernetesUpgrade.go
- tests/extensions/provisioning/provision.go
- tests/extensions/provisioning/scale.go
- tests/extensions/rbac/rbac.go
- tests/nodescaling/scale_hosted_test.go
- tests/nodescaling/scale_test.go
- tests/provisioning/README.md
- tests/provisioning/provision_hosted_test.go
- tests/provisioning/provision_test.go
- tests/psact/psact_test.go
- tests/rbac/README.md
- tests/rbac/rbac_test.go
- tests/snapshot/snapshot.go
- tests/snapshot/snapshot_restore_test.go
- tests/upgrading/kubernetes_hosted_test.go
- tests/upgrading/kubernetes_upgrade_test.go
This PR provides initial support for RBAC. It will provision clusters and assign a cluster owner and project member to the cluster utilizing Rancher2 Terraform resources only.
Additionally, general refactoring to adjust to RBAC (and other functionalities) has been done as well.
> Add initial RBAC support to tfp-automation

- tests/rbac/README.md
The RBAC README has an example config for the authentication providers, but not for the other RBAC tests. This small PR includes an example so that you don't have to reference the `provisioning` README.
> Update RBAC README to have an example

- tests/snapshot/snapshot_restore_test.go
`tfp-automation` allows for the `etcd` block to be optional in the configuration file. This line, however, is causing the test to fail if it is not defined. `etcd` block is only needed when working with S3-enabled clusters. Otherwise, it should remain optional.
> Remove unncessary not nil line

- config/config.go
- pipeline/qase/results/results.go
- pipeline/scripts/build_qase_reporter.sh
- tests/nodescaling/README.md
- tests/nodescaling/scale_hosted_test.go
- tests/nodescaling/scale_test.go
- tests/provisioning/README.md
- tests/provisioning/provision_hosted_test.go
- tests/provisioning/provision_test.go
- tests/psact/README.md
- tests/psact/psact_test.go
- tests/rbac/README.md
- tests/rbac/auth_test.go
- tests/rbac/rbac_test.go
- tests/snapshot/README.md
- tests/snapshot/snapshot_restore_test.go
- tests/upgrading/README.md
- tests/upgrading/kubernetes_hosted_test.go
- tests/upgrading/kubernetes_upgrade_test.go
Currently, we utilize Qase for our test results during release testing. However, we only have the ability to do so via Jenkins. It would be desirable to have an option to locally report results as well, should we need to do so.
This PR gives the ability to do just that.
> Add support to locally report results to Qase

- config/nodeproviders/vsphere/vsphereConfig.go
Found that I could not set cloudConfig in the vsphereConfig block under terraform section correctly. Shepard would read the value, but would not write it to the file. Thank you Sam for helping figure out it was the typo probably causing an issue with the json to yaml conversion.
> Fixing Typo in Json Tag for CloudConfig

- Dockerfile
- Jenkinsfile
Updating the Jenkinsfile and Dockerfile to ensure that tfp-automation is using the standard Jenkins PEM files. We still have the ability to use custom PEM files when locally testing. However, for Jenkins testing, we will use the standard PEM files as we do in rancher/rancher.
> Updates to use standard Jenkins pem files

- tests/rancher2/nodescaling/scale_test.go
This is causing the `nodescaling` tests to not function correctly as we are passing in the incorrect client.
> Remove admin client from nodescaling tests

- README.md
- config/config.go
- framework/set/defaults/defaults.go
- framework/set/provisioning/nodedriver/rke2k3s/setConfig.go
Adding support to change CNI for nodedriver clusters. Also adding kubeproxyless setups, but adding a Chart Values section and ability to disable kube proxy.
Example of a terraform section using these settings.
```
terraform:
module: vsphere_rke2
clusterName: test
chartValues: |-
rke2-cilium:
k8sServiceHost: 127.0.0.1
k8sServicePort: 6443
kubeProxyReplacement: true
cni: cilium
disable-kube-proxy: true
```
> Added chartValues and machineGlobalConfigValue to rke2k3s

- config/config.go
- config/nodeproviders/aws/awsConfig.go
- framework/set/provisioning/airgap/registerPrivateNodes.go
- framework/set/provisioning/airgap/setConfig.go
- framework/set/provisioning/custom/rke2k3s/setRancher2ClusterV2.go
- framework/set/provisioning/nodedriver/rke2k3s/setConfig.go
- framework/set/provisioning/nodedriver/rke2k3s/setPrivateRegistry.go
- framework/set/resources/airgap/aws/createResources.go
- framework/set/resources/airgap/createMainTF.go
- framework/set/resources/airgap/rancher/setup.sh
- framework/set/resources/airgap/rancher/setupAirgapRancher.go
- framework/set/resources/airgap/rke2/createAirgapCluster.go
- framework/set/resources/registries/auth-registry.sh
- framework/set/resources/registries/createRegistry.go
- framework/set/resources/registries/non-auth-registry.sh
- framework/set/resources/rke/rke/createCluster.go
- framework/set/resources/sanity/aws/instances.go
- framework/set/resources/sanity/rke2/createCluster.go
- framework/wait/state/activeCluster.go
- modules/airgap/outputs.tf
- tests/airgap/README.md
- tests/airgap/airgap_provisioning_test.go
- tests/extensions/provisioning/verify.go
Currently, airgap tests require that you bring your own authenticated private registry, prior to running the test. During release testing, this is not ideal. We need to be able to run the test and a private registry is created and then the test is ran. This PR adds support for the following:
- Authenticated private registries
- Non-authenticated private registries
These are written in a modular way so that we can use these for private registry tests down the line. In addition, `VerifyCluster` is enhanced to check if the pods have the registry prefix.
> Add support for authenticated and unauthenticated private registries

- framework/set/provisioning/nodedriver/rke2k3s/setConfig.go
- framework/set/provisioning/nodedriver/rke2k3s/setEtcdConfig.go
- framework/set/provisioning/providers/aws/awsProviders.go
During on of our reworks/updates to cluster provisioning we inadvertently broke s3 by generating the cloud credential name during the creation process. 
Note: at some point in the future we should separate the config build stage from the creation logic so things don't get out of sync like this.
> Fix s3 cloud credential

- config/config.go
- framework/set/resources/airgap/createMainTF.go
- framework/set/resources/airgap/rke2/add-servers.sh
- framework/set/resources/airgap/rke2/createAirgapCluster.go
- framework/set/resources/airgap/rke2/init-server.sh
- framework/set/resources/registries/createMainTF.go
- framework/set/resources/registries/createRegistry/auth-registry.sh
- framework/set/resources/registries/createRegistry/createRegistry.go
- framework/set/resources/registries/createRegistry/non-auth-registry.sh
- framework/set/resources/registries/rancher/setup.sh
- framework/set/resources/registries/rke2/add-servers.sh
- framework/set/resources/registries/rke2/createCluster.go
- framework/set/resources/registries/rke2/init-server.sh
- framework/set/resources/rke/createRKEMainTF.go
- tests/airgap/README.md
- tests/infrastructure/README.md
- tests/infrastructure/setup_airgap_rancher_test.go
- tests/infrastructure/setup_airgap_rke2_test.go
- tests/infrastructure/setup_proxy_rancher_test.go
- tests/infrastructure/setup_rancher_test.go
- tests/infrastructure/setup_rke1_test.go
- tests/infrastructure/setup_rke2_test.go
- tests/proxy/README.md
- tests/registries/README.md
- tests/rke/README.md
- tests/rke/rke_provider_test.go
- tests/sanity/README.md
A talking point on the team for quite some time has been a desire to have side "tests" that will various types of infrastructure. These can be standalone clusters or just different permutations of Rancher. As this framework has evolved over time, this increasingly has been more of a need to have.
This PR creates an `infrastructure` folder that does just that. This helps to keep the overall objective of the repo to testing the Rancher2 Terraform provider, while also having a dedicated location for creating infrastructure.
In addition, enhanced the following:
- Prime support for airgap and private registries tests
- Removed authenticated registry for airgap tests - Rancher officially only supports unauthenticated registry for the system default registry
> Add infrastructure folder and Prime support for registries

- defaults/modules/modules.go
- framework/set/provisioning/airgap/register-nodes.sh
- framework/set/provisioning/airgap/registerPrivateNodes.go
- framework/set/provisioning/airgap/setRKE1Config.go
- framework/set/provisioning/airgap/setRKE2K3SConfig.go
- framework/set/provisioning/custom/rke1/setConfig.go
- framework/set/provisioning/custom/rke1/setRancher2Cluster.go
- framework/set/provisioning/multiclusters/setMultiCluster.go
- framework/set/resources/airgap/rancher/setup.sh
- framework/set/resources/airgap/rancher/setupAirgapRancher.go
- framework/set/resources/registries/createRegistry/auth-registry.sh
- framework/set/resources/registries/createRegistry/non-auth-registry.sh
- framework/set/resources/registries/rancher/createRancher.go
- framework/set/resources/registries/rancher/setup.sh
- framework/set/setConfigTF.go
- tests/airgap/airgap_provisioning_test.go
- tests/extensions/provisioning/supportedModules.go
- tests/infrastructure/README.md
For the airgap tests, we currently only support RKE2/K3s. While RKE1 is slated to be deprecated soon, we should still it for release testing purposes mainly in the meantime. This PR adds support for RKE1 to the airgap tests.
Additionally, this PR supports pulling and pushing images to private registries in parallel. We're starting off with 10 images at a time. If we see issues, we will decrease the number, but this help to speed up relevant tests.
> Add RKE1 support to airgap test and speed up private registries

- defaults/keypath/keypath.go
- defaults/modules/modules.go
- framework/set/defaults/defaults.go
- framework/set/provisioning/airgap/nullresource/setAirgapNullResource.go
- framework/set/provisioning/airgap/setRKE1Config.go
- framework/set/provisioning/airgap/setRKE2K3SConfig.go
- framework/set/provisioning/imported/import-nodes.sh
- framework/set/provisioning/imported/importNodes.go
- framework/set/provisioning/imported/importedRKE1Config.go
- framework/set/provisioning/imported/importedRKE2K3SConfig.go
- framework/set/provisioning/imported/setImportedCluster.go
- framework/set/provisioning/multiclusters/setMultiCluster.go
- framework/set/resources/imported/createRKE2K3SCluster.go
- framework/set/resources/k3s/createCluster.go
- framework/set/resources/k3s/init-server.sh
- framework/set/resources/rancher2/setProvidersAndUsersTF.go
- framework/set/setConfigTF.go
- modules/airgapRKE2/main.tf
- modules/airgapRKE2/outputs.tf
- tests/extensions/provisioning/supportedModules.go
- tests/infrastructure/setup_airgap_rke2_test.go
- tests/rancher2/provisioning/README.md
- tests/rancher2/provisioning/provision_hosted_test.go
- tests/rancher2/provisioning/provision_import_test.go
- tests/rancher2/upgrading/kubernetes_hosted_test.go
- tests/rancher2/upgrading/kubernetes_upgrade_test.go
Out of the broader effort to fully move away from Corral, one of the release test tasks is importing clusters. Not only is it using Corral, it is limited in only doing K3s. This PR goes and adds support for importing RKE1, RKE2 and K3s HA clusters.
> Add support for imported clusters for RKE1/RKE2/K3S

- .golangci.yaml
- tests/airgap/airgap_provisioning_test.go
- tests/extensions/provisioning/verify.go
- tests/proxy/proxy_provisioning_test.go
- tests/proxy/proxy_upgrade_rancher_test.go
- tests/rancher2/provisioning/provision_import_test.go
In this current release testing iteration, it was found that some test cases do not have unique names. Primarily, airgap and proxy are interchanging reports when they shouldn't.
Also, it was noted that the workload tests are not consistently pulling an `nginx` image. This is due to a Docker Hub pull throttle issue. This causes tests to provision clusters, but not finish all of the post cluster checks. As such, we need to disable for now until we can find a reliable, consistent solution.
> Fix Qase names for release testing and temporarily disable workload checks

- tests/airgap/airgap_provisioning_test.go
- tests/extensions/provisioning/verify.go
- tests/proxy/proxy_provisioning_test.go
- tests/proxy/proxy_upgrade_rancher_test.go
- tests/rancher2/nodescaling/scale_test.go
- tests/rancher2/provisioning/provision_import_test.go
- tests/rancher2/rbac/rbac_test.go
- tests/rancher2/snapshot/snapshot_restore_test.go
- tests/rancher2/upgrading/kubernetes_upgrade_test.go
- tests/registries/registries_test.go
The previous PR that aimed to skip the workload tests was actually marking the whole test as skipped. To get around this, we're just going to remove the call from the relevant release testing based tests.
> Remove the workloads function from each test

- config/nodeproviders/aws/awsConfig.go
- defaults/resourceblocks/nodeproviders/amazon/amazonBlocks.go
- framework/set/provisioning/nodedriver/rke1/setConfig.go
- framework/set/provisioning/providers/aws/awsMachineConfig.go
- framework/set/provisioning/providers/aws/awsProviders.go
- tests/airgap/README.md
- tests/proxy/README.md
- tests/rancher2/provisioning/README.md
- tests/rancher2/rbac/README.md
- tests/registries/README.md
- tests/sanity/README.md
Found a bug with rke1 not setting the SSH user which causes node drivers to error out on all non-ubuntu images. 
Added a field for volumeType to allow gp3 ami's to function
> Fix rke1 SSH user and add volumeType

- framework/set/resources/registries/createRegistry/non-auth-registry.sh
- tests/airgap/airgap_provisioning_test.go
- tests/airgap/airgap_upgrade_rancher_test.go
The Windows airgap tests were previously removed as they were not consistently provisioning the RKE2 Windows clusters. Troubleshooting further, `skopeo` was not collecting all of the needed manifests each run. As a result, switched to `crane` and have consistenetly had the clusters provision.
Additionally, needed to pull `rancher/rke2-runtime`, `rancher/rke2-runtime-windows-amd64`, `mirrored-pause` and all of the architectures to assist in properly getting Windows clusters to come up with all workloads active.
> Fix airgap Windows tests

- config/config.go
- framework/set/provisioning/nodedriver/rke2k3s/setConfig.go
- tests/rancher2/snapshot/snapshot.go
- tests/rancher2/snapshot/snapshot_restore_test.go
Our recent changes broke snapshot testing. This fix updates the snapshot tests to remove unused fields and upgrading as part of the snapshot test case since this isn't really testing anything in the terraform provider.
> Fix snapshots

- Jenkinsfile_harvester
- Jenkinsfile_vpn
- framework/set/resources/airgap/rancher/setupAirgapRancher.go
- framework/set/resources/airgap/rke2/createAirgapCluster.go
- framework/set/resources/k3s/createCluster.go
- framework/set/resources/proxy/createMainTF.go
- framework/set/resources/proxy/rancher/createRancher.go
- framework/set/resources/proxy/rancher/upgradeRancher.go
- framework/set/resources/proxy/rke2/createCluster.go
- framework/set/resources/proxy/squid/createSquidProxy.go
- framework/set/resources/rancher2/setKeyPath.go
- framework/set/resources/registries/createRegistry.go
- framework/set/resources/registries/createRegistry/createRegistry.go
- framework/set/resources/registries/rancher/createRancher.go
- framework/set/resources/registries/rke2/createCluster.go
- framework/set/resources/rke/rke/clusterCheck.go
- framework/set/resources/rke2/createCluster.go
- framework/set/resources/sanity/rancher/createRancher.go
- tests/infrastructure/setup_proxy_rancher_test.go
adding logic to use goroot variable to use go on systems with it defined. If it is not defined, fallback to the existing code. 
The existing code wasn't working on my machine as-is so this is a workaround to fix it
> allow usage from user-defined GOROOT

- .github/workflows/verify-changes.yaml
- Dockerfile
- defaults/clustertypes/clustertypes.go
- defaults/modules/modules.go
- framework/set/defaults/defaults.go
- framework/set/provisioning/custom/nullresource/customNullResource.go
- framework/set/provisioning/custom/rke2k3s/setConfig.go
- framework/set/provisioning/imported/importNodes.go
- framework/set/provisioning/imported/importedRKE1Config.go
- framework/set/provisioning/imported/importedRKE2K3SConfig.go
- framework/set/provisioning/imported/nullresource/importNullResource.go
- framework/set/resources/imported/createRKE2K3SCluster.go
- framework/set/resources/k3s/add-servers.sh
- framework/set/resources/k3s/createCluster.go
- framework/set/resources/k3s/init-server.sh
- framework/set/resources/providers/vsphere/provider.go
- framework/set/resources/providers/vsphere/virtualMachine.go
- framework/set/resources/providers/vsphere/virtualMachineTemplate.go
- framework/set/resources/rancher2/setProvidersAndUsersTF.go
- framework/set/setConfigTF.go
- go.mod
- tests/extensions/provisioning/supportedModules.go
- tests/rancher2/provisioning/README.md
- tests/rancher2/provisioning/provision_import_test.go
This PR allows vSphere to be an option when creating an imported cluster (RKE1/RKE2/K3S). For release testing purposes, EC2 will still be used, but the DynamicInput function will allow you to specify EC2 or vSphere. Additionally, this PR bumps Go version to `1.24`.
> Add vSphere support for imported clusters

- .github/workflows/sanity-test.yaml
Small PR that adds a cron job to the newly added `sanity-test.yaml` to run Monday-Friday.
> Add cron job to sanity test

- .github/workflows/sanity-test.yaml
- tests/sanity/sanity_provisioning_test.go
As discussed offline, per recurring runs ongoing work, we will need to ensure that we have respective Qase IDs per each release in the cycle. This PR does that.
> Update Qase reporting per release line

- .github/actions/revoke-runner-ip/action.yaml
- .github/actions/whitelist-runner-ip/action.yaml
- .github/workflows/pr-sanity-test.yaml
- .github/workflows/recurring-proxy-test.yaml
- .github/workflows/recurring-proxy-upgrade-test.yaml
- .github/workflows/recurring-sanity-test.yaml
- framework/set/resources/upgrade/createMainTF.go
GHA workflows to support weekly recurring runs for proxy + proxy upgrade `tfp-automation` tests.
Also, made a small semantic update to sanity workflow environments.
> implement recurring runs for proxy + proxy upgrade suites

- .github/workflows/pr-sanity-test.yaml
- .github/workflows/recurring-proxy-test.yaml
- .github/workflows/recurring-proxy-upgrade-test.yaml
- .github/workflows/recurring-sanity-test.yaml
- .github/workflows/recurring-sanity-upgrade-test.yaml
- .github/workflows/verify-changes.yaml
- tests/proxy/proxy_provisioning_test.go
- tests/proxy/proxy_upgrade_rancher_test.go
Upon any failures seen in any of the workflows, we need to be able to have failures reported to our Qase test runs. As of now, only successes get reported, but we need all statuses shown. Additionally, updated the proxy tests to get the date and time as there are now GHA workflows we run weekly.
> Add if always to reporting steps for GHA

- .github/workflows/proxy-test.yaml
- .github/workflows/proxy-upgrade-test.yaml
- .github/workflows/sanity-test.yaml
- .github/workflows/sanity-upgrade-test.yaml
As per offline discussions, we want to ensure that we have a means to have our recurring runs and release testing work together. An easy way to do this is to leverage just one YAML for each test. We do this by setting a default value when on a schedule and for release testing, we manually trigger the workflow with inputted values.
Long term, the goal is to ensure that we have a trigger in `rancher/rancher` so when a new alpha/RC is cut, the release testing portion automatically will occur. But this will be a workaround in the meantime.
> Consolidate recurring and release testing workflows

- .github/workflows/airgap-test.yaml
- .github/workflows/airgap-upgrade-test.yaml
- .github/workflows/pr-sanity-test.yaml
- .github/workflows/proxy-test.yaml
- .github/workflows/proxy-upgrade-test.yaml
- .github/workflows/registry-test.yaml
- .github/workflows/sanity-test.yaml
- .github/workflows/sanity-upgrade-test.yaml
The scheduled sanity job failed. Looking into it, it's because the rancher and qase versions were empty. Upon further investigation, we simply need to just ensure that in a scenario where we have a scheduled run, we update our conditionals for that.
> Update rancher and qase versions for scheduled runs

- .github/workflows/proxy-test.yaml
- .github/workflows/proxy-upgrade-test.yaml
- .github/workflows/sanity-test.yaml
- .github/workflows/sanity-upgrade-test.yaml
Like description says, updating missed areas for updated Rancher and Qase versions from the last PR. Testing in the PR worked, but did not once merged as these updates weren't existing.
> Update missed areas for rancher and qase versions

- .github/workflows/rancher2-recurring-test.yaml
- framework/set/provisioning/imported/import-nodes.sh
- tests/airgap/README.md
- tests/proxy/README.md
- tests/rancher2/nodescaling/README.md
- tests/rancher2/provisioning/README.md
- tests/rancher2/psact/README.md
- tests/rancher2/rbac/README.md
- tests/rancher2/recurring/README.md
- tests/rancher2/recurring/recurring_test.go
- tests/rancher2/snapshot/README.md
- tests/rancher2/snapshot/snapshot.go
- tests/rancher2/snapshot/snapshot_restore_test.go
- tests/rancher2/upgrading/README.md
- tests/registries/README.md
- tests/rke/README.md
- tests/sanity/README.md
To build upon the GHA workflows that we have the infrastructure-based tests, this PR extends that functionality to the Rancher2 tests. The idea is that eventually, we can have this as a template for the `rancher/tests` for release testing as well.
> Add recurring runs for Rancher2 tests

- framework/set/provisioning/airgap/copyScriptToBastion.go
- framework/set/provisioning/airgap/register-nodes.sh
- framework/set/provisioning/airgap/register-windows-nodes.sh
- framework/set/provisioning/airgap/registerPrivateNodes.go
- framework/set/provisioning/airgap/setRKE1Config.go
- framework/set/provisioning/airgap/setRKE2K3SConfig.go
- framework/set/provisioning/airgap/setWindowsConfig.go
- tests/airgap/airgap_provisioning_test.go
- tests/airgap/airgap_upgrade_rancher_test.go
For a few releases now, the airgap test has been flaky. Specifically, when registering nodes, sometimes it will go without issue, other times, the first airgap node would not even register. Spending some time looking into it, it's because we were using an outdated `ssh` command.
I have updated that and have not seen issues, hoping this fixes it longterm.
> Remove ssh -o ProxyCommand to fix flaky airgap test

- .github/workflows/check-rancher-tag.yaml
- tests/infrastructure/README.md
It was noted that we are overriding versions every time the check rancher tag workflow happens. We need to not do this, otherwise, the workflow will never work.
> Write new tag to file only if a new version is found

- .github/workflows/check-rancher-tag.yaml
Now that we have the check rancher tag working, I am going to temporarily disable the cron job. Just until we can fix the caching issue so that once every 4 hours is up, it's not constantly running against every same tag.
> Temporarily comment out cron job for check rancher tag

- .github/workflows/rancher2-recurring-test.yaml
The `rancher2-recurring-test.yaml` is missing the `workflow_call` block and has outdated if conditionals in the jobs. This is leading to issues when the check rancher tag workflow kicks off against new Rancher tags. This should alleviate those issues seen.
> Add workflow_call and update jobs in recurring-test

- .github/workflows/airgap-test.yaml
- .github/workflows/airgap-upgrade-test.yaml
- .github/workflows/pr-sanity-test.yaml
- .github/workflows/proxy-arm64-test.yaml
- .github/workflows/proxy-test.yaml
- .github/workflows/proxy-upgrade-arm64-test.yaml
- .github/workflows/proxy-upgrade-test.yaml
- .github/workflows/rancher2-recurring-test.yaml
- .github/workflows/registry-test.yaml
- .github/workflows/sanity-arm64-test.yaml
- .github/workflows/sanity-test.yaml
- .github/workflows/sanity-upgrade-arm64-test.yaml
- .github/workflows/sanity-upgrade-test.yaml
Currently, our revoke ip action intermittently hits the following error, resulting in the whitelisted IP not getting revoked or properly cleaned up:
```
An error occurred (RequestExpired) when calling the DescribeManagedPrefixLists operation: Request has expired.
```
This is likely due to the temporary AWS credentials expiring before the revoke ip action is called.
This PR aims to resolve this by refreshing the credentials before revoking the ip, which ensures the credentials used to revoke the ip are valid before sending out that request.
> fix revoke ip failure

- .github/workflows/registry-test.yaml
The registry workflow was failing due to their being an excess Configure AWS credentials step. We need to remove this to have the workflow properly work.
> Update registry to remove excess AWS credentials

- .github/workflows/airgap-test.yaml
- .github/workflows/airgap-upgrade-test.yaml
- .github/workflows/registry-test.yaml
As title, says reverting recent changes done during this release testing cycle. Additionally, removing the `needs-on` in each subsequent step for airgap and registry workflows. Realistically, we aren't going to receive all of the alphas at the same time.
> Revert recent changes and remove needs-on

- framework/set/provisioning/imported/import-nodes.sh
- tests/airgap/airgap_provisioning_test.go
- tests/infrastructure/acceptEULA.go
- tests/rancher2/recurring/recurring_test.go
This PR mainly updates the `import-nodes.sh` used in the import cluster tests to support both `x86` and `arm64` architectures; ARM64 images fail without this fix. Also, fixing misc. petty changes in airgap and recurring runs test.
> Enhance imported clusters to support ARM64

- .github/workflows/check-rancher-tag.yaml
`check-rancher-tag` has an interesting issue where it appears randomly that the `actions/cache` is not properly acknowledging saved cached versions. Looking deeper into this, I noted there is a critical pattern; when PRs are open, subsequent `check-rancher-tag` workflows kicked off don't respect the prior caching.
This PR does a couple of things:
- Prohibits `check-rancher-tag` from running unless it's explicitly by the main branch, or from the schedule
- Updates the static name from `rancher-tag-cache` to `rancher-tag-cache-`; this is to add more safeguards that unique caches are created and do not overwrite the main cache
> Fix caching issue when PRs are open

- framework/set/resources/rke2/add-servers.sh
- framework/set/resources/rke2/createCluster.go
- framework/set/resources/rke2/init-server.sh
There is inconsistency with the RKE2 cluster creation when dealing with the sanity Rancher. This job adds retry logic in case it fails and makes sure that we are using the private IP and not the FQDN.
> Refactor RKE2 cluster creation for sanity Rancher

- .github/workflows/check-rancher-tag.yaml
This PR aims to enhance our caching in GHA for `tfp-automation` to utilize S3 buckets instead of the built-in GHA solution, which unfortunately only preserves data for a maximum of 7 days, leading to instability and weekly maintenance.
> enhance rancher tag cache to use s3

- .github/workflows/sanity-test.yaml
- .github/workflows/sanity-upgrade-test.yaml
- framework/set/provisioning/custom/sleep/setSleep.go
- framework/set/provisioning/imported/importNodes.go
- framework/set/provisioning/imported/importedRKE2K3SConfig.go
- framework/set/resources/imported/addWindowsNode.go
- framework/set/resources/imported/createRKE2K3SCluster.go
- framework/set/resources/providers/aws/windowsInstances.go
- framework/set/resources/rancher2/setProvidersAndUsersTF.go
- framework/set/resources/rke2/add-servers.sh
- framework/set/resources/rke2/init-server.sh
As part of a recent change to ensure standard users are provisioning clusters, the Windows imported cluster test was overlooked. Specifically, we have a time sleep after creating the standard user. However, there is also a time sleep in the Windows import test.
The solution is adding a `suffix` parameter in the time sleep resource. That way, you will never have two time sleeps that are the exact same.
Outside of that, removing the scheduling of 2.9 sanity as we only need to run it against check rancher tag at this point.
> Fix duplicate time sleep issue with Windows imported clusters

- framework/set/resources/airgap/rancher/setup.sh
- framework/set/resources/airgap/rancher/upgrade.sh
- framework/set/resources/proxy/rancher/setup.sh
- framework/set/resources/proxy/rancher/upgrade.sh
- framework/set/resources/registries/rancher/setup.sh
- framework/set/resources/sanity/rancher/setup.sh
- framework/set/resources/sanity/rancher/upgrade.sh
Testing the staging registry has a community Rancher UI by default. While not ideal, this PR tries to mimic Prime UI by modifying the environment variables to mirror what Prime does. As we cannot control what images are pushed into a staging registry, this is the next best thing.
> Update staging registry UI to be Prime-like

- framework/set/provisioning/imported/importNodes.go
- framework/set/provisioning/imported/importedRKE2K3SConfig.go
- framework/set/provisioning/imported/nullresource/importNullResource.go
- framework/set/resources/imported/addWindowsNode.go
- framework/set/resources/imported/createRKE2K3SCluster.go
The import cluster module-based tests are failing specifically in Jenkins. Looking deeper into it, this is because we were using the outdated method to get the user directory. Locally and GHA are fine with that method, but Jenkins specifically would fail.
Updated to the method in which all of them will work fine. Additionally, did some general cleanup.
> Fixing Jenkins path in import tests + general cleanup

- framework/set/resources/airgap/rancher/setup.sh
- framework/set/resources/airgap/rancher/setupAirgapRancher.go
- framework/set/resources/proxy/rancher/createRancher.go
- framework/set/resources/proxy/rancher/setup.sh
- framework/set/resources/registries/rancher/createRancher.go
- framework/set/resources/registries/rancher/setup.sh
- framework/set/resources/sanity/rancher/createRancher.go
- framework/set/resources/sanity/rancher/setup.sh
In light of the docker rate limit, further investigation into that revealed a side issue. Specifically, all of the nodes in the RKE2 local cluster may or may not be in a state of `Ready`. That is an issue because when you try to install cert manager pods, this may fail. And if those don't fail, installing Rancher will because all of the RKE2 specific pods will not be up due to all of the nodes not being Ready.
To fix this, I am checking the status to make sure the cluster is ready.
> Add local cluster checks before setting up Rancher

- .github/workflows/proxy-test.yaml
- .github/workflows/proxy-upgrade-test.yaml
- .github/workflows/rancher2-recurring-test.yaml
- .github/workflows/sanity-test.yaml
- .github/workflows/sanity-upgrade-test.yaml
- framework/set/provisioning/nodedriver/rke2k3s/createRegistrySecret.go
- framework/set/provisioning/nodedriver/rke2k3s/setPrivateRegistry.go
Now that we have more stability with the QA private registry, when running a sanity upgrade, it was revealed that duplicate secret names are being made. To get around this, we will just make the name unique to the cluster name.
> Fix duplicate registry secret issue for upgrading tests

- tests/registries/registries_test.go
this appropriately declares standaloneConfig to be referenced by VerifyRancherVersion
> reference to undeclared var causes panic

- .github/workflows/airgap-upgrade-test.yaml
- framework/set/resources/airgap/rancher/setup.sh
- framework/set/resources/airgap/rancher/upgrade.sh
When running airgap upgrade GHA, few issues were spotted:
- v2.12 is using `alpha` as the repo instead of `latest`. This causes issues as it needs to be `latest` initially when setting up the released version. The other jobs are correctly using `upgrade-prime-staging`
- The internal FQDN is getting patched, but Rancher needs to be restarted for the change to take impact
> Fix airgap internal FQDN patching

- tests/infrastructure/createRancher.go
Further looking into the last PR, the actual issue of the internal FQDN is part of the recent QOL refactor, the incorrect FQDN is called for `PostRancherSetup`. Past code verified this as well, this needs to be `AirgapInternalFQDN`. The last PR is still a good enhancement to have, but this is the actual issue.
> Fix FQDN for PostRancherSetup for airgap installs

- framework/set/resources/registries/createRegistry/auth-registry.sh
Enhance script for auth registries, to log in to authenticated private registry before pulling and pushing docker images.
This PR also updates REGISTRY_USERNAME and REGISTRY_PASSWORD params to be more specific to our Docker account, as to not cause confusion between the authenticated registry username and password params
> Fix auth registries

- .github/actions/get-qase-id/action.yaml
- .github/workflows/airgap-test.yaml
- .github/workflows/airgap-upgrade-test.yaml
- .github/workflows/check-rancher-tag.yaml
- .github/workflows/proxy-arm64-test.yaml
- .github/workflows/proxy-test.yaml
- .github/workflows/proxy-upgrade-arm64-test.yaml
- .github/workflows/proxy-upgrade-test.yaml
- .github/workflows/rancher2-recurring-test.yaml
- .github/workflows/registry-test.yaml
- .github/workflows/sanity-arm64-test.yaml
- .github/workflows/sanity-test.yaml
- .github/workflows/sanity-upgrade-arm64-test.yaml
As part of post release cycle, we want to consolidate the Qase reporting for recurring runs and release testing. Moving forward, we will have the following:
- Recurring test run
- RC test run
> Consolidate Qase reporting parameters

- framework/set/resources/ipv6/rke2/add-servers.sh
- framework/set/resources/ipv6/rke2/init-server.sh
When testing IPv6, there was a small issue I noted with connecting to the airgapped nodes. The registry YAML is not creating and it is because it is trying to connect to the public IP and not the private IP. This small PR fixes that.
> Fix SSH connectivity with IPv6 RKE2 cluster

- .github/workflows/community-proxy-test.yaml
- .github/workflows/community-sanity-test.yaml
Non upgrade proxy and sanity are still failing and it's because we need the chart version to be set like the Rancher version in the prior PR.
> Update chart version for manually ran head workflows

- .github/workflows/community-airgap-test.yaml
- .github/workflows/community-airgap-upgrade-test.yaml
- .github/workflows/community-registry-test.yaml
- .github/workflows/prime-airgap-test.yaml
- .github/workflows/prime-airgap-upgrade-test.yaml
- .github/workflows/prime-registry-test.yaml
The check rancher tag is having issues when running the airgap and private registry workflows. Through some deep diving, it is speculated that the issue pertains to `workflow_dispatch`. Specifically, there are secrets that may not be properly getting set. This is further backed by the point that when manually ran, it is working fine.
> Update the rancher version and chart version for airgap/registry

- .github/workflows/post-release-upgrade.yaml
- .github/workflows/proxy-test.yaml
- .github/workflows/proxy-upgrade-test.yaml
- .github/workflows/rancher2-recurring-test.yaml
- .github/workflows/sanity-upgrade-test.yaml
Last PR neglected to have `github.event.inputs.rancher_version` in the relevant portions of the workflow.
> Fix workflow_dispatch in relevant workflows

- pipeline/qase/reporter/main.go
- pipeline/qase/schemaParams.go
- tests/airgap/README.md
- tests/proxy/README.md
- tests/registries/README.md
- tests/sanity/README.md
When reporting to Qase for post release checks, it would be nice to be able to display the Rancher type of Community/Prime. Specifically, when a release has both Community and Prime, this is especially more desirable. This PR updates the Qase schemas to show this information.
> Update Qase reporter to display Rancher type

- README.md
Small PR to add GHA results to the parent README. It will be helpful to have these displayed at the repo level as a quick glance as what is passing and what is failing.
> Add GHA workflow results to README
